### DISCUSSION TITLE
Trainer Summary

### DISCUSSION THREAD

**Discussion by yashkant** [Lightning-AI/pytorch-lightning#13082] [Idea pool]
Hi! 

Thanks for the amazing lib! I try out a lot of codebases using PL, and all of them have config files nested and hidden somewhere in code. 

It would be pretty cool if we could print a summary of trainer -- I am thinking logger paths, metrics etc with a method. 

I started with PL only a few months ago, so I might be missing if this feature already exists.

**Comment by akihironitta** [comment]
@yashkant `LightningCLI` may be something you're looking for!

Running the script with `LightningCLI` used:
```console
$ python main.py --print_config
```
will output:
```yaml
# pytorch_lightning==1.7.0dev
seed_everything: true
trainer:
  logger: false
  enable_checkpointing: false
  callbacks: null
...
```

See more details here: https://pytorch-lightning.readthedocs.io/en/stable/common/lightning_cli.html
