### DISCUSSION TITLE
Pass through **kwargs in yaml config file

### DISCUSSION THREAD

**Discussion by wwbrannon** [Lightning-AI/pytorch-lightning#13081] [Lightning Trainer API: Trainer, LightningModule, LightningDataModule] [answered]
Hi all,

I'd like to pass through arguments in a yaml config file which are not declared with type hints in the classes receiving them, but are instead parsed out of **kwargs. Jsonargparse doesn't like this and complains that it needs type hints. Is there a simple way to do this? I'm aware I can define wrapper subclasses that declare the arguments in their `__init__` methods, but that seems like a hack.

For example, here's a snippet I'd like to use:
```
strategy:                                                                       
    class_path: pytorch_lightning.strategies.DDPStrategy                        
    init_args:                                                                  
        process_group_backend: gloo                                             
        find_unused_parameters: false                                           
```

Here's what jsonargparse has to say about that:
```
jsonargparse.util.ParserError: Parser key "trainer.strategy": Value "Namespace(class_path='pytorch_lightning.strategies.DDPStrategy', init_args=Namespace(parallel_devices=None, cluster_
environment=None, checkpoint_io=None, precision_plugin=None, ddp_comm_state=None, model_averaging_period=None, process_group_backend='gloo', find_unused_parameters=False))" does not val
idate against any of the types in typing.Union[str, pytorch_lightning.strategies.strategy.Strategy, NoneType]:
  - Expected a <class 'str'> but got "Namespace(class_path='pytorch_lightning.strategies.DDPStrategy', init_args=Namespace(parallel_devices=None, cluster_environment=None, checkpoint_io
=None, precision_plugin=None, ddp_comm_state=None, model_averaging_period=None, process_group_backend='gloo', find_unused_parameters=False))"
  - Problem with given class_path "pytorch_lightning.strategies.DDPStrategy":
    - 'Configuration check failed :: No action for destination key "find_unused_parameters" to check its value.'
  - Expected a <class 'NoneType'> but got "Namespace(class_path='pytorch_lightning.strategies.DDPStrategy', init_args=Namespace(parallel_devices=None, cluster_environment=None, checkpoi
nt_io=None, precision_plugin=None, ddp_comm_state=None, model_averaging_period=None, process_group_backend='gloo', find_unused_parameters=False))"
```
