### DISCUSSION TITLE
Instantiate custom ClusterEnvironment from LightningCLI

### DISCUSSION THREAD

**Discussion by Darktex** [Lightning-AI/pytorch-lightning#13156] [Lightning Trainer API: Trainer, LightningModule, LightningDataModule]
Love the LightningCLI API! According to the [docs](https://pytorch-lightning.readthedocs.io/en/stable/common/lightning_cli.html), we seem to be able to register only callbacks and not generic plugins.

I was wondering if there was any workaround for ClusterEnvironments. In my case, I don't necessarily need to construct the ClusterEnvironment from CLI as it will always be launched there. I just don't want to lose the other goodies of LightningCLI and revert back to the "old" argparse style...

**Comment by mauvilsa** [comment]
The registries are being deprecated, see https://github.com/PyTorchLightning/pytorch-lightning/pull/13221. The only benefit that the registries provided was being able to specify a class just by its name instead of the full class path. You should be able to configure environments just like it is done for callbacks. It would be specifying elements in the `trainer.plugins` list. Something like:

```yaml
trainer:
  plugins:
    - class_path: pytorch_lightning.plugins.environments.SLURMEnvironment
      init_args:
        auto_requeue: true
```
