### DISCUSSION TITLE
How to pass a reference to a function in yaml config file

### DISCUSSION THREAD

**Discussion by kenenbek** [Lightning-AI/pytorch-lightning#13613] [Lightning Trainer API: Trainer, LightningModule, LightningDataModule] [answered]
If I want to use CLI to initialize datamodule object I should use:

`python train.py  --config data.yaml`

```
data:
  class_path: foo.datasets.my_data
  init_args:
    data_dir: data
```

But what if one the `init_arguments` is a function? How can I pass a reference to it like this? 

```
data:
  class_path: foo.datasets.my_data
  init_args:
    data_dir: data
    filter: foo.datasets.filter1
```

`foo.datasets.filter1` is a function.

Thank you for attention.

**Comment by tshu-w** [comment]


**Reply by kenenbek** [reply]
Why it is possible to use `class_path`, but not `function_path` in yaml?

**Reply by tshu-w** [reply]
For a detailed reason, I thought you might ask mauvilsa at https://github.com/omni-us/jsonargparse.

**Reply by mauvilsa** [reply]
From jsonargparse v4.30.0, it is now allowed to give the import path of a function in `class_path`. In `init_args` the parameters to the function would be expected. Though, it is required that the function have as return annotation a subclass of the typehint.

**Comment by mauvilsa** [comment, marked as answer]
This is supported in jsonargparse. Just use `Callable` as type hint, see its mention in the [docs](https://jsonargparse.readthedocs.io/en/stable/#type-hints). Basically you would have:
```python
class MyData:
    def __init__(self, data_dir: str, filter: Callable):
        ...
```
Then the config could be as you had it:
```yaml
class_path: foo.datasets.my_data
init_args:
  data_dir: data
  filter: foo.datasets.filter1
```
Or `filter` could be a class that once instantiated becomes callable, like:
```yaml
class_path: foo.datasets.my_data
init_args:
  data_dir: data
  filter:
    class_path: path.to.callable.class
    init_args:
      param1: val1
      ...
```

**Reply by barucden** [reply]
Related question: when instantiating a class, is it possible to pass a function that returns an instance of the given class?

The following is possible

```python
class Test:
    def __init__(self, x: MyClass):
        ...

class MyClass:
    ...
```
```yaml
class_path: path.to.Test
init_args:
  x: 
    class_path: path.to.MyClass
```

But this does not work for me:
```python
def create_myclass() -> MyClass:
    return MyClass()
```
```yaml
class_path: path.to.Test
init_args:
  x: 
    class_path: path.to.create_myclass # it's not really a class_path
```

I guess there is a way ([docs](https://jsonargparse.readthedocs.io/en/stable/index.html#classes-from-functions)), but I can't figure out how to do it from the YAML config. I get errors like `"path.to.create_myclass" is not a subclass of <class 'path.to.MyClass'>`.

**Reply by mauvilsa** [reply]
`class_from_function` only works when manually adding a class argument. It would probably work if you change the type hint to `x: Union[MyClass, Callable[..., MyClass]]` and in the yaml `x: path.to.create_myclass`. Though note that currently for a `Callable` the parser does not validate the return type. The path to any function will be accepted and the failure will be somewhere else due to the return being unexpected.

**Reply by chenjoya** [reply]
Hi, it seems that lightning CLI can not still parse the function to an instantiated class, like the above scenario. More specific,

```yaml
class_path: torchvision.models.detection.retinanet_resnet50_fpn_v2
init_args:
  weights: DEFAULT
```

I can only obtain ```dict``` type by this. It cannot support instantiating an object detector (nn.Module). Could you tell me how to do? Thank you.
