### DISCUSSION TITLE
Change the scheduler interval in CLI

### DISCUSSION THREAD

**Discussion by ForJadeForest** [Lightning-AI/pytorch-lightning#13975] [Lightning Trainer API: Trainer, LightningModule, LightningDataModule] [answered]
I just trying to use `StepLR`  in my `.yaml` config. 
```yaml
lr_scheduler:
  class_path: StepLR
  init_args:
    step_size : 10
    gamma : 0.5
```
I guess the CLI will set the `interval` as "epoch", but I want to use the "step" to control my learning rate.  I do not find anything about it in the docs. How can achieve it just in my `.yaml` file?
