### DISCUSSION TITLE
Is it possible to pass arguments to callbacks in the LightningCLI?

### DISCUSSION THREAD

**Discussion by cgoliver** [Lightning-AI/pytorch-lightning#14339] [Lightning Trainer API: Trainer, LightningModule, LightningDataModule] [answered]
For example, if I wanted to set the option for `write_interval` in the [BasePredictionWriter](https://pytorch-lightning.readthedocs.io/en/stable/_modules/pytorch_lightning/callbacks/prediction_writer.html#BasePredictionWriter) from the LightningCLI's `trainer.callbacks` flag, would there be a syntax for this? As far as I can tell, one can only pass the name of the callback class.

**Comment by mauvilsa** [comment, marked as answer]
The syntax is described in https://pytorch-lightning.readthedocs.io/en/stable/cli/lightning_cli_advanced_3.html#trainer-callbacks-and-arguments-with-class-type. As command line arguments would be:
```shell
$ python ... \
    --trainer.callbacks+=BasePredictionWriter \
    --trainer.callbacks.write_interval=batch \
    ...
```
Or in a config file:
```yaml
trainer:
  callbacks:
    - class_path: BasePredictionWriter
      init_args:
        write_interval: batch
```
