### DISCUSSION TITLE
How to pass a type(not an object) to a class with lightningcli?

### DISCUSSION THREAD

**Discussion by calvinzhan** [Lightning-AI/pytorch-lightning#14552] [Lightning Trainer API: Trainer, LightningModule, LightningDataModule] [answered]
I want to pass a type(not an object) to a subclass of LightningDataModule.  I did the following, but it seemed lightningcli tried to initialize an object and complain required fileds were missing. How can I do that?

```
class TxtDataModule(LightningDataModule):
    def \__init\__(
        self,
        domain_dataset: Dataset,
        ...
    ):
       dataset_obj = domain_dataset(....)
       ...
```

in yaml
```
data:
  class_path: src.training.data_module.data_module_txt.TxtDataModule
  init_args:
    domain_dataset: src.training.semantic_sim.dataset_txt.TxtDataset_LoadFromFile  # a subclass of Dataset
```
