### DISCUSSION TITLE
Passing transforms to datamodule from LightningCLI example

### DISCUSSION THREAD

**Discussion by cgoliver** [Lightning-AI/pytorch-lightning#14607] [Lightning Trainer API: Trainer, LightningModule, LightningDataModule] [answered]
Would appreciate if someone has an example of passing a list of transforms with arguments to a Lightning DataModule from the LightningCLI.

I'm thinking of a syntax similar to [this](https://pytorch-lightning.readthedocs.io/en/stable/cli/lightning_cli_advanced_3.html#trainer-callbacks-and-arguments-with-class-type) where one can pass multiple callables from the CLI. 

EDIT: I managed to pass a single transform by adding the `transforms: Optional[Callable] = None,` typing hint to my datamodule `__init__()` but I get an unrecognized argument error when using the `data.transforms+=my.transforms.Transform` syntax in the CLI.

Thanks!

**Comment by tshu-w** [comment, marked as answer]
You should use list, for more details, see https://jsonargparse.readthedocs.io/en/stable/#type-hints

**Comment by SinaSarparast** [comment]
I'm also trying to initiate transformations and pass them to the data module. I use the following config for the data module:
```
data:
  class_path: pfp.data.data_loader.DataLoaderIter
  init_args:
    batch_size: 2
    pyg_file_dir: ./pyg_dataset
    transformations:
      - class_path: torch_geometric.transforms.center.Center
```
When debugging this is parsed as :

`transformations = [{'class_path': 'torch_geometric.tran...ter.Center'}] `

The object is not initiated like the callbacks that are passed to the trainer. Is this how it should be or I'm doing something wrong?
