### DISCUSSION TITLE
Lightning CLI and config.yaml structure for multiple Trainer subcommands

### DISCUSSION THREAD

**Discussion by alzaia** [Lightning-AI/pytorch-lightning#15507] [Lightning Trainer API: Trainer, LightningModule, LightningDataModule]
Hello, I'm trying to group all my Trainer subcommands and args in the same config.yaml file while making use of the Lightning CLI. The structure of my config.yaml would be something like this:
```
fit:
  model: ...
  trainer:
    max_epochs: ...
    accelerator: ...
    ...
  data: ...
predict:
  ckpt_path: ...
```
And then I would use this an input when I'm fitting the model:
```
python trainer.py --config config.yaml fit
```
Or this command when I rather just want to predict:
```
python trainer.py --config config.yaml predict
```

What is the standard (cleaner) way of doing this?
