### DISCUSSION TITLE
epoch/step validation with MLflowLogger

### DISCUSSION THREAD

**Discussion by kota-iizuka** [Lightning-AI/pytorch-lightning#19187] [code help: CV]
I'm trying to perform a 100 step experiment on a dataset with 1 epoch = 22 steps and logging every 10 steps by `MLFlowLogger`, but it doesn't work.

The settings for the Trainer are as follows

````yaml
   max_epochs: null
   max_steps: 100
   val_check_interval: 10
   check_val_every_n_epoch: null
````

I am using mlflow logger and the output image is as below.

<img width="421" alt="image" src="https://github.com/Lightning-AI/pytorch-lightning/assets/64062831/395481b1-1f21-4f60-824a-4657637a68ea">

Judging from the graph, it appears that even though `check_val_every_n_epoch` is set to `None`, validation is occurring at the end of each epoch and at the end of `trainer.fit()`, and the epoch number is incorrectly recorded as step.

Is there a setting to resolve this? Or do I need to modify pytorch-lightning itself?
