### DISCUSSION TITLE
About save_hyperparameter() implementation for yaml init config

### DISCUSSION THREAD

**Discussion by Ya88012** [Lightning-AI/pytorch-lightning#20518] [General]
Hi everyone,  
I am a beginner with PyTorch Lightning and have encountered an issue related to `save_hyperparameters()`. After reading the official documentation, I understand that `save_hyperparameters()` is used to save arguments for the LightningModule. However, I noticed that it doesn't save the model's initialization arguments. 

For context, I am using WandB to log all parameters, but it only shows the parameters passed into the LightningModule, not the ones used to initialize the model, which I defined in a YAML configuration file.  

I just do not know whether this is my coding, deliberate designed, or wandb's problem.
I’m wondering if I need to adjust my coding style or if there’s a better way to implement this to work seamlessly with WandB. Any advice would be appreciated!

Thanks your time in advance!

This is the part of my yaml for the experiment:

```
model:
    lr: 5e-7
    beta_1: 0.9
    beta_2: 0.999
    weight_decay: 1e-5
    warmup_steps: 10000
    max_steps: 100000
    warmup_start_lr: 1e-8
    eta_min: 1e-8
    pretrained_path: ''
    using_global_pretrain: False
    use_local_pos_embed: False

    net:
        class_path: climax.arch.ClimaXPatchMask
        init_args:
            img_size: [140, 180]
            patch_size: 4
            embed_dim: 1024
            depth: 8
            decoder_depth: 2
            num_heads: 16
            mlp_ratio: 4
            drop_path: 0.1
            drop_rate: 0.1
            mask_ratio: 0.5
```

The wandb overview output after save_hyperparameter:

![image](https://github.com/user-attachments/assets/44bfaa03-dcc8-4fa3-bd3f-60223635244a)
