### ISSUE TITLE
Extending Argument Linking for more complicate relationship

### ISSUE THREAD

**Issue by Boltzmachine** [Lightning-AI/pytorch-lightning#19717]
### Description & Motivation

In current argument linking, two linked arguments must be the same. However, sometimes I want some more complex relationship between them. For example, `a = b + 1`.

### Pitch

Argument linking is a very good feature. However, sometimes I am frustrated when two arguments are not the same but are just correlated, e.g. require some math transformation

```yaml
data:
    num_classes: 2
model:
    init_args:
        output_dim: data.num_classes + 1
```

cc @borda @carmocca @mauvilsa
