### ISSUE TITLE
Construct objects from yaml by classmethod

### ISSUE THREAD

**Issue by Boltzmachine** [Lightning-AI/pytorch-lightning#19801]
### Description & Motivation

Sometimes I want to construct an object from classmethods (e.g. `from_pretrained`) instead of `__init__`. But looks like currently lightning does not support it

### Pitch

```
model:
    class_path: Model.from_pretrained
    init_args:
        ...
```

**Comment by mauvilsa** [comment]
In https://github.com/omni-us/jsonargparse/pull/513 support was added to give a function (including classmethods) to `class_path`. This became available since jsonargparse v4.30.0, which was released 18 June 2024, after this issue was created. I don't know if for the specific case that @Boltzmachine was trying this works now. But would make sense to try again to see whether this is already supported.

**Comment by SkafteNicki** [comment]
@mauvilsa thanks for confirming that this is possible.
Here is a example script and config that works as intended:
```python
import torch
import torch.nn as nn
from lightning.pytorch import LightningModule, LightningDataModule
from lightning.pytorch.cli import LightningCLI
from torch.utils.data import DataLoader, TensorDataset


class MyModel(LightningModule):
    def __init__(self, hidden_size: int = 64, num_classes: int = 10):
        super().__init__()
        self.save_hyperparameters()
        self.net = nn.Sequential(
            nn.Linear(784, hidden_size),
            nn.ReLU(),
            nn.Linear(hidden_size, num_classes)
        )
    
    @classmethod
    def from_pretrained(cls, num_classes: int = 10) -> "MyModel":
        print("🎯 SUCCESS: from_pretrained classmethod called!")
        instance = cls(hidden_size=128, num_classes=num_classes)
        return instance
    
    def forward(self, x):
        return self.net(x.view(x.size(0), -1))
    
    def training_step(self, batch, batch_idx):
        x, y = batch
        logits = self(x)
        loss = nn.functional.cross_entropy(logits, y)
        self.log('train_loss', loss)
        return loss
    
    def configure_optimizers(self):
        return torch.optim.Adam(self.parameters(), lr=0.001)


class DemoData(LightningDataModule):
    def __init__(self, batch_size: int = 32):
        super().__init__()
        self.batch_size = batch_size
    
    def setup(self, stage=None):
        x = torch.randn(200, 1, 28, 28)
        y = torch.randint(0, 5, (200,))
        dataset = TensorDataset(x, y)
        self.train_dataset = dataset
        self.val_dataset = dataset
    
    def train_dataloader(self):
        return DataLoader(self.train_dataset, batch_size=self.batch_size, shuffle=True)

if __name__ == "__main__":
    cli = LightningCLI(
        model_class=None, 
        datamodule_class=None,
        save_config_callback=None,
    )
```
```yaml
model:
  class_path: __main__.MyModel.from_pretrained
  init_args:
    num_classes: 5

data:
  class_path: __main__.DemoData
  init_args:
    batch_size: 16

trainer:
  accelerator: cpu
  max_epochs: 2
  limit_train_batches: 3
  limit_val_batches: 2
  logger: false
  enable_checkpointing: false
  enable_progress_bar: true
  enable_model_summary: false
```
Closing issue.
