### ISSUE TITLE
Multiple subclassing levels required to use LightningDataModule in LightningCLI

### ISSUE THREAD

**Issue by jasonkena** [Lightning-AI/pytorch-lightning#20024]
### Bug description

I get the following error message
```error: Parser key "data":
  Import path data.snemi.SNEMIDataModule does not correspond to a subclass of LightningDataModule
```
with yaml config
```yaml
data:
  class_path: data.snemi.SNEMIDataModule
```
when defining SNEMIDataModule as follows
```python
class SNEMIDataModule(LightningDataModule):
    ...
```
this problem is solved by creating a dummy subclass:
```python
class DummyDataModule(LightningDataModule):
    pass
class SNEMIDataModule(DummyDataModule):
    ...
```
Is this intended behavior?

### What version are you seeing the problem on?

v2.2

### Error messages and logs

```
# Error messages and logs here please
```

### Environment

<details>
  <summary>Current environment</summary>

```
#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow):
#- PyTorch Lightning Version (e.g., 1.5.0):
#- Lightning App Version (e.g., 0.5.2):
#- PyTorch Version (e.g., 2.0):
#- Python version (e.g., 3.9):
#- OS (e.g., Linux):
#- CUDA/cuDNN version:
#- GPU models and configuration:
#- How you installed Lightning(`conda`, `pip`, source):
#- Running environment of LightningApp (e.g. local, cloud):
```

</details>

**Comment by jasonkena** [comment]
Hmm, the problem seems to be related to using `lightning.LightningDataModule` instead of `pytorch_lightning.LightningDataModule`

**Comment by awaelchli** [comment]
Hi @jasonkena 

Mixing imports would definitely not be good. Can you make sure to use consistently only `lightning` imports everywhere in your program?

For further help, can I ask you to fill out the full bug report template?

**Comment by SkafteNicki** [comment]
Old issue, but for future reference can confirm that the issue seems to stem from mixing imports. Simple example to reproduce:
```python
from lightning.pytorch.cli import LightningCLI

if __name__ == "__main__":
    cli = LightningCLI(
        model_class=None,
        datamodule_class=None,
        save_config_callback=None,
    )
```
with this config:
```yaml
model:
  class_path: pytorch_lightning.demos.boring_classes.BoringModel
data:
  class_path: pytorch_lightning.demos.boring_classes.BoringDataModule
```
running `python main.py fit -c config.yaml` returns the error
```
pytorch_lightning.demos.boring_classes.BoringModel does not correspond to a subclass of LightningModule
```
and a similar one for the data which is the same error as in the issue description. Changing to same import style in config:
```yaml
model:
  class_path: lightning.demos.boring_classes.BoringModel
data:
  class_path: lightning.demos.boring_classes.BoringDataModule
```
fixes the problem. Closing issue.
