### ISSUE TITLE
LightningCLI doesn't save optimizer's configuration if not explicitly given

### ISSUE THREAD

**Issue by adosar** [Lightning-AI/pytorch-lightning#20103]
### Bug description

From the [Docs](https://lightning.ai/docs/pytorch/stable/cli/lightning_cli_advanced.html#automatic-save-of-config):

> To ease experiment reporting and reproducibility, by default LightningCLI automatically saves the full YAML configuration in the log directory. After multiple fit runs with different hyperparameters, each one will have in its respective log directory a config.yaml file.

I would expect the saved `config.yaml` to include the options for `--optimizer` etc. even if they were not passed, just like it populates the `config.yaml` with  `--seed_everything` even if it wasn't explicitly passed in the CLI.

### What version are you seeing the problem on?

v2.2

### How to reproduce the bug

```python
# main.py
from lightning.pytorch.cli import LightningCLI

# simple demo classes for your convenience
from lightning.pytorch.demos.boring_classes import DemoModel, BoringDataModule


def cli_main():
    cli = LightningCLI(DemoModel, BoringDataModule)
    # note: don't call fit!!


if __name__ == "__main__":
    cli_main()
```

Now from the console:
```console
python main.py fit --trainer.max_epochs=1
```

### Error messages and logs
The `config.yaml` under `lightning_logs/version_0` is this:

```yaml
# lightning.pytorch==2.2.1
seed_everything: 0
trainer:
  accelerator: auto
  strategy: auto
  devices: auto
  num_nodes: 1
  precision: null
  logger: null
  callbacks: null
  fast_dev_run: false
  max_epochs: 1
  min_epochs: null
  max_steps: -1
  min_steps: null
  max_time: null
  limit_train_batches: null
  limit_val_batches: null
  limit_test_batches: null
  limit_predict_batches: null
  overfit_batches: 0.0 
  val_check_interval: null
  check_val_every_n_epoch: 1
  num_sanity_val_steps: null
  log_every_n_steps: null
  enable_checkpointing: null
  enable_progress_bar: null
  enable_model_summary: null
  accumulate_grad_batches: 1
  gradient_clip_val: null
  gradient_clip_algorithm: null
  deterministic: null
  benchmark: null
  inference_mode: true
  use_distributed_sampler: true
  profiler: null
  detect_anomaly: false
  barebones: false
  plugins: null
  sync_batchnorm: false
  reload_dataloaders_every_n_epochs: 0
  default_root_dir: null
model:
  out_dim: 10
  learning_rate: 0.02
ckpt_path: null
```

### Environment

<details>
  <summary>Current environment</summary>

```
#- PyTorch Lightning Version (e.g., 1.5.0):
#- PyTorch Version (e.g., 2.0):
#- Python version (e.g., 3.9):
#- OS (e.g., Linux):
#- CUDA/cuDNN version:
#- GPU models and configuration:
#- How you installed Lightning(`conda`, `pip`, source):
```

</details>

cc @carmocca @mauvilsa
